- id: pygeoapi_resources_have_links
  name: pygeoapi_resources_have_links
  description: Check that pygeoapi resources have the proper links to the source and/or documentation
  entry: pygeoapi_resources_have_links
  language: python
  files: \.(yaml|yml)$
  types: [python]
  stages: [pre-commit, pre-merge-commit, manual]
  pass_filenames: false